# Generated by Django 3.0.8 on 2020-10-02 02:05

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('name_display', models.CharField(default='Your name here', max_length=127)),
                ('intro_text', models.CharField(default='Intro Text', help_text='Text to display in the middle of the banner', max_length=255)),
                ('bio', wagtail.core.fields.RichTextField(blank=True)),
                ('banner_image', models.ForeignKey(blank=True, help_text='Wide Welcome Banner Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('profile_pic', models.ForeignKey(blank=True, help_text='Profile Picture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PageEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('descrip', models.TextField(blank=True, null=True)),
                ('edu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
