# Generated by Django 3.0.8 on 2020-10-07 21:21

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201002_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageeducation',
            name='descrip',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
