# Generated by Django 3.0.8 on 2020-10-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201007_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageeducation',
            name='logo',
        ),
        migrations.AddField(
            model_name='pageeducation',
            name='school',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='pageeducation',
            name='time_period',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
