# Generated by Django 3.0.8 on 2020-10-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_pageeducation_school_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageeducation',
            old_name='school',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='pageeducation',
            old_name='school_site',
            new_name='location_site',
        ),
    ]
