# Generated by Django 3.0.8 on 2020-10-22 18:28

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201022_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperiencePairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('location', models.CharField(blank=True, max_length=63, null=True)),
                ('location_site', models.URLField(blank=True, max_length=255, null=True)),
                ('time_period', models.CharField(blank=True, max_length=63, null=True)),
                ('descrip', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_pairs', to='home.HomePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
