# Generated by Django 3.0.8 on 2020-10-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_experiencepairs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageEducation',
        ),
    ]
