# Generated by Django 3.0.8 on 2020-10-22 18:50

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_pageeducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='edu_history',
            field=wagtail.core.fields.StreamField([('item', wagtail.core.blocks.StructBlock([('location', wagtail.core.blocks.CharBlock(max_length=63, required=True)), ('location_site', wagtail.core.blocks.URLBlock(max_length=255, required=True)), ('time_period', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=True))]))], null=True),
        ),
    ]
