# Generated by Django 3.0.8 on 2020-10-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_homepage_work_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExperiencePairs',
        ),
    ]
