# Generated by Django 3.0.8 on 2020-10-26 18:18

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_experiencepairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='motivation',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='motivation_header',
            field=models.CharField(default='Motivation', help_text='Title for motivation section', max_length=255),
        ),
    ]
