# Generated by Django 3.0.8 on 2020-11-10 15:46

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201028_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='edu_history',
            field=wagtail.core.fields.StreamField([('item', wagtail.core.blocks.StructBlock([('location', wagtail.core.blocks.CharBlock(max_length=63, required=True)), ('location_site', wagtail.core.blocks.URLBlock(max_length=255, required=True)), ('time_period', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=True)), ('associated_image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='work_history',
            field=wagtail.core.fields.StreamField([('item', wagtail.core.blocks.StructBlock([('location', wagtail.core.blocks.CharBlock(max_length=63, required=True)), ('location_site', wagtail.core.blocks.URLBlock(max_length=255, required=True)), ('time_period', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=True)), ('associated_image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], null=True),
        ),
    ]
